CDK stuff from MFP (#139927)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -11,28 +11,28 @@ export REGION_A=us-east-1
 export PROJECT=carts
 
 # check node exists
-if ! which node > /dev/null ; then
-	echo "node not found on the system. Install version in .nvmrc based on instructions in README"
-	exit 1
+if ! which node >/dev/null; then
+    echo "node not found on the system. Install version in .nvmrc based on instructions in README"
+    exit 1
 fi
 
 # check node version
-if ! diff .nvmrc <(node -v) > /dev/null ; then
-	echo "Uh Oh! The current node version does not match the version required in .nvmrc"
-	echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
-	echo "If you don't have nvm yet, the instructions in the README should sort you."
-	echo "** Don't forget to add the bit to your shell profile **"
-	exit 1
+if ! diff .nvmrc <(node -v) >/dev/null; then
+    echo "Uh Oh! The current node version does not match the version required in .nvmrc"
+    echo "If you have installed nvm, simply running 'nvm use' in this directory should solve the problem"
+    echo "If you don't have nvm yet, the instructions in the README should sort you."
+    echo "** Don't forget to add the bit to your shell profile **"
+    exit 1
 fi
 
 # check yarn exists
-if ! which yarn > /dev/null ; then
-	echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
-	exit 1
+if ! which yarn >/dev/null; then
+    echo "yarn not found on the system. On macOS, you can install it with 'brew install yarn'"
+    exit 1
 fi
 
 # check serverless is installed globally.
-if ! which serverless > /dev/null || ! serverless --version 2>&1 | grep -q "Framework 4."; then
+if ! which serverless >/dev/null || ! serverless --version 2>&1 | grep -q "Framework 4."; then
     echo "installing serverless v4 globally"
     yarn global add serverless@4.4.18
     export PATH="$PATH:$(yarn global bin)"
@@ -41,8 +41,8 @@ fi
 # have to ensure that yarn install is up to date.
 # we use .yarn_install as a marker for the last time `yarn install` was run. Rerun the command when yarn.lock is updated
 if [ "yarn.lock" -nt ".yarn_install" ]; then
-	yarn install
-	touch .yarn_install
+    yarn install
+    touch .yarn_install
 fi
 
 # Parse arguments
@@ -51,20 +51,16 @@ ARGS=()
 
 for arg in "$@"; do
     case $arg in
-        --update-env)
+    update-env)
         UPDATE_ENV=true
         ;;
-        *)
-        ARGS+=("$arg")
-        ;;
     esac
+    ARGS+=("$arg")
 done
 
-# Inject secrets to .env if the flag is set
 if [ "$UPDATE_ENV" = true ]; then
-    # Check if 1Password CLI is installed
-    if ! which op > /dev/null; then
-        echo "The MDCT team uses 1Password to store and retrieve development credentials. If you do not have a 1Password account please request one."
+    if ! which op >/dev/null; then
+        echo "The MDCT team uses 1Password to store and retrieve development credentials. On macOS, you can install it with 'brew install --cask 1password-cli'"
         exit 1
     fi
 
@@ -75,6 +71,8 @@ if [ "$UPDATE_ENV" = true ]; then
     sed -i "" -e "s/# pragma: allowlist secret//g" services/ui-src/.env
 fi
 
+yarn
+
 # build and run run.ts
 # tsc is configured to build what we expect in tsconfig.json
-./node_modules/.bin/tsc && node ./build_dev/run.js "${ARGS[@]-}"
+./node_modules/.bin/tsc && node ./build_dev/src/run.js "${ARGS[@]-}"
